apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /home/kundamnikhil/databricks-airflow3.0-template/databricks-airflow3.0-template/tmp/logs
        containerPath: /mnt/airflow-data/logs
